CREATE TABLE `ticket` (
  `TICKET_ID` INT NOT NULL AUTO_INCREMENT,
  `TITLE` VARCHAR(1024) NULL,
  `CONTENT` MEDIUMTEXT NULL,
  `STATUS` SMALLINT(2) NULL,
  `CREATED_DATE` DATETIME NULL,
  PRIMARY KEY (`TICKET_ID`));
  
ALTER TABLE `ticket` 
ADD COLUMN `FROM_USER` INT(11) NOT NULL AFTER `CREATED_DATE`,
ADD COLUMN `TO_USER` INT(11) NOT NULL AFTER `FROM_USER`,
ADD INDEX `TICKET_FROM_USER_USER_idx` (`FROM_USER` ASC),
ADD INDEX `TICKET_TO_USER_USER_idx` (`TO_USER` ASC);
ALTER TABLE `ticket` 
ADD CONSTRAINT `TICKET_FROM_USER_USER`
  FOREIGN KEY (`FROM_USER`)
  REFERENCES `user` (`USER_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT `TICKET_TO_USER_USER`
  FOREIGN KEY (`TO_USER`)
  REFERENCES `user` (`USER_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `ticket` 
ADD COLUMN `TYPE` TINYINT(2) NULL AFTER `TO_USER`,
ADD COLUMN `REF_ID` INT(11) NULL AFTER `TYPE`;

ALTER TABLE `ticket`
CHANGE COLUMN `CREATED_DATE` `CREATED_DATE` DATETIME NULL AFTER `REF_ID`;
  
  
CREATE TABLE `ticket_conv` (
  `TICKET_CONV_ID` INT NOT NULL AUTO_INCREMENT,
  `TICKET_ID` INT NOT NULL,
  `OWNER` INT(11) NULL,
  `DATE` DATETIME NULL,
  `CONTENT` MEDIUMTEXT NULL,
  PRIMARY KEY (`TICKET_CONV_ID`),
  INDEX `TICKET_CONV_USER_idx` (`OWNER` ASC),
  INDEX `TICKET_CONV_TICKET_idx` (`TICKET_ID` ASC),
  CONSTRAINT `TICKET_CONV_TICKET`
    FOREIGN KEY (`TICKET_ID`)
    REFERENCES `ticket` (`TICKET_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `TICKET_CONV_USER`
    FOREIGN KEY (`OWNER`)
    REFERENCES `user` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
